CREATE DATABASE login_db;
USE login_db;
CREATE TABLE user(
id INT NOT NULL AUTO_INCREMENT,
email VARCHAR(30) NOT NULL,
username VARCHAR(30) NOT NULL,
name VARCHAR(30) NOT NULL,
password VARCHAR(30) NOT NULL,
primary key(id)
);

